# Generated by Django 4.2.1 on 2023-05-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0002_alter_student_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="request_method",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
